import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Products",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<section className="mx-auto max-w-screen-2xl p-12">{children}</section>
				<footer className="text-center text-sm text-gray-400">
					<p>© 2024</p>
				</footer>
			</body>
		</html>
	);
}
